---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "hosts.yaml"
        group_file: "groups.yml"
        defaults_file: "defaults.yml"
runner:
    plugin: threaded
    options:
        num_workers: 100
