---
sw1:
  hostname: 192.168.59.10
  username: python
  password: '123456'
  groups:
      - huawei

sw2:
  hostname: 192.168.59.20
  groups:
      - huawei

sw3:
    hostname: 192.168.59.30
    groups:
      - huawei

sw4:
    hostname: 192.168.59.40
    groups:
      - huawei

sw5:
    hostname: 192.168.59.50
    groups:
      - huawei
...