---
sw1:
    hostname: 192.168.11.11
    username: python
    password: '123'
    groups:
        - huawei_group1
    data:
        building: '1'
        level: '1'
sw2:
    hostname: 192.168.11.12
    groups:
        - huawei_group1
    data:
        building: '1'
        level: '2'
sw3:
    hostname: 192.168.11.13
    groups:
        - huawei_group2
    data:
        building: '2'
        level: '1'
sw4:
    hostname: 192.168.11.14
    groups:
        - huawei_group2
    data:
        building: '2'
        level: '2'