---
sw1:
    hostname: 192.168.11.11
    username: python
    password: '123'
    groups:
        - huawei_group1
sw2:
    hostname: 192.168.11.12
    groups:
        - huawei_group1

sw3:
    hostname: 192.168.11.13
    groups:
        - huawei_group2

sw4:
    hostname: 192.168.11.14
    groups:
        - huawei_group2